name: "Let me lint:fix that for you"

on: [push]

permissions:
  contents: write

jobs:
  LMLFTFY:
    runs-on: ubuntu-latest
    steps:
    - name: "Check out Git repository"
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
    - name: "Use Node.js 22"
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af #v4.1.0
      with:
        node-version: 22
    - name: "Install application"
      run: |
        npm install --ignore-scripts
        cd frontend
        npm install --ignore-scripts --legacy-peer-deps
    - name: "Fix everything which can be fixed"
      run: 'npm run lint:fix'
    - name: Commit lint fixes
      run: |
        git config user.name JuiceShopBot
        git config user.email 61591748+JuiceShopBot@users.noreply.github.com
        git add --all

        if git diff --cached --quiet; then
          echo "No lint fixes to commit."
          exit 0
        fi

        git commit --signoff --message "Auto-fix linting issues"
        git push origin "HEAD:${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}"
